name: Custom Actions
on: push
jobs: 
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Jose"
      -  run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
